//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AREA
    {
        public AREA()
        {
            this.DISTRIBUTION_HOUSES = new HashSet<DISTRIBUTION_HOUSES>();
        }
    
        public int REGION_ID { get; set; }
        public int AREA_ID { get; set; }
        public string AREA_NAME { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string REMARKS { get; set; }
    
        public virtual REGION REGION { get; set; }
        public virtual ICollection<DISTRIBUTION_HOUSES> DISTRIBUTION_HOUSES { get; set; }
    }
}
