//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_POSITIONS
    {
        public int DISTRIBUTION_HOUSE_ID { get; set; }
        public int CM_POSITION_ID { get; set; }
        public string CM_POSITION_NAME { get; set; }
        public Nullable<int> POSITION_TYPE_ID { get; set; }
        public Nullable<int> MS_ID { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
    }
}
