//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplainTicket
    {
        public ComplainTicket()
        {
            this.TICKET_REPLIED = new HashSet<TICKET_REPLIED>();
        }
    
        public int TicketId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public Nullable<int> Mobile { get; set; }
        public string Title { get; set; }
        public string ContentText { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LastReplyFrom { get; set; }
        public Nullable<System.DateTime> LastReplyDate { get; set; }
        public Nullable<bool> isNotifyByEmail { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Remarks { get; set; }
    
        public virtual TICKET_CATEGORY TICKET_CATEGORY { get; set; }
        public virtual TICKET_STATUS TICKET_STATUS { get; set; }
        public virtual TICKET_SUB_CATEGORY TICKET_SUB_CATEGORY { get; set; }
        public virtual ICollection<TICKET_REPLIED> TICKET_REPLIED { get; set; }
    }
}
