//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRIBUTION_HOUSE_MAIN
    {
        public int HouseId { get; set; }
        public string HouseName { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<int> DISTRICT_ID { get; set; }
        public Nullable<int> THANA_ID { get; set; }
        public string PHONE { get; set; }
        public string CONTACT_PERSON { get; set; }
        public Nullable<int> DESIGNATION_ID { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string REMARKS { get; set; }
    }
}
