//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDUCATIONAL_DEGREES
    {
        public int EDUCATIONAL_DEGREE_ID { get; set; }
        public string EDUCATIONAL_DEGREE_NAME { get; set; }
        public Nullable<int> EDUCATIONAL_DEGREE_LEVEL_ID { get; set; }
        public string REMARKS { get; set; }
    }
}
