//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public EMPLOYEE()
        {
            this.EMPLOYEE_DISTRIBUTION_HOUSES = new HashSet<EMPLOYEE_DISTRIBUTION_HOUSES>();
            this.EMPLOYEE_WORK = new HashSet<EMPLOYEE_WORK>();
        }
    
        public int EMPLOYEE_ID { get; set; }
        public int PERSON_ID { get; set; }
        public Nullable<int> EMPLOYEE_TYPE_ID { get; set; }
        public string EMPLOYEE_CODE_ { get; set; }
        public string EMPLOYEE_CODE { get; set; }
        public Nullable<int> SUPERVISOR_ID { get; set; }
        public Nullable<System.DateTime> JOINING_DATE { get; set; }
        public Nullable<long> MINIMUM_INVESTMENT { get; set; }
        public string OTHER_FINANCIAL { get; set; }
        public string SERVICE_DESCRIPTION { get; set; }
        public string PREVIOUS_PD_DETAIL { get; set; }
        public Nullable<int> EMPLOYEE_ROLE_STATUS_ID { get; set; }
        public Nullable<int> DISTRIBUTION_HOUSE_ID { get; set; }
        public Nullable<int> LOCATION_ID { get; set; }
        public Nullable<int> OFFICE_ID { get; set; }
        public int DESIGNATION_ID { get; set; }
        public Nullable<int> BRAND_ID { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<bool> SIGNATURE_PRESENT { get; set; }
        public string SIGNATURE_PATH { get; set; }
        public Nullable<bool> PHOTO_PRESENT { get; set; }
        public string PHOTO_PATH { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CRAETED_DATE { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public Nullable<int> BANK_ID { get; set; }
        public string BANK_BRANCH { get; set; }
        public string BANK_ACCOUNT_NO { get; set; }
    
        public virtual DISTRIBUTION_HOUSES DISTRIBUTION_HOUSES { get; set; }
        public virtual ICollection<EMPLOYEE_DISTRIBUTION_HOUSES> EMPLOYEE_DISTRIBUTION_HOUSES { get; set; }
        public virtual ICollection<EMPLOYEE_WORK> EMPLOYEE_WORK { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
