//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_WORK
    {
        public int WORK_ID { get; set; }
        public int EMPLOYEE_ID { get; set; }
        public string WORK_AREA { get; set; }
        public string UNION_NAME { get; set; }
        public string THANA_NAME { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string REMARKS { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
