//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormPDEmplyeeView
    {
        public int FormId { get; set; }
        public int PollidutId { get; set; }
        public string PERSON_NAME { get; set; }
        public int SupervisorId { get; set; }
        public int DistributionHouseId { get; set; }
        public string FormCode { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> DeliveryTotalPrice { get; set; }
        public Nullable<bool> Active { get; set; }
        public int DISTRIBUTION_HOUSE_ID { get; set; }
        public string DISTRIBUTION_HOUSE_NAME { get; set; }
    }
}
