//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORM_ROW_ITEM
    {
        public int RowId { get; set; }
        public int FormId { get; set; }
        public int ProductSKUId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> DeliveryUnitPrice { get; set; }
        public Nullable<int> JCOffer { get; set; }
        public Nullable<int> IndentCartonQty { get; set; }
        public Nullable<int> IndentPieceQty { get; set; }
        public Nullable<int> DeliveryCartoonQty { get; set; }
        public Nullable<int> DeliveryPieceQty { get; set; }
        public Nullable<int> DeliveryOffer { get; set; }
        public Nullable<decimal> ITotalPrice { get; set; }
        public Nullable<decimal> IDDAmount { get; set; }
        public Nullable<decimal> INetPrice { get; set; }
        public Nullable<decimal> DTotalPrice { get; set; }
        public Nullable<decimal> DDDAmount { get; set; }
        public Nullable<decimal> DNetPrice { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Reamrks { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual PD_PRODUCT_INDENT_FORM PD_PRODUCT_INDENT_FORM { get; set; }
        public virtual PRODUCT_SKU PRODUCT_SKU { get; set; }
    }
}
