//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class JCOffer
    {
        public int ID { get; set; }
        public int ProductSKUId { get; set; }
        public Nullable<int> JCOfferValue { get; set; }
        public Nullable<int> JCOfferUnit { get; set; }
        public Nullable<int> OutOf { get; set; }
        public Nullable<int> OutOfType { get; set; }
        public Nullable<System.DateTime> OfferStartDate { get; set; }
        public Nullable<System.DateTime> OfferEndDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Remarks { get; set; }
    
        public virtual PRODUCT_SKU PRODUCT_SKU { get; set; }
    }
}
