//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PD_PRODUCT_INDENT_FORM
    {
        public PD_PRODUCT_INDENT_FORM()
        {
            this.FORM_ROW_ITEM = new HashSet<FORM_ROW_ITEM>();
        }
    
        public int FormId { get; set; }
        public int PollidutId { get; set; }
        public int SupervisorId { get; set; }
        public int DistributionHouseId { get; set; }
        public string FormCode { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> DeliveryTotalPrice { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<FORM_ROW_ITEM> FORM_ROW_ITEM { get; set; }
    }
}
