//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_DETAILS
    {
        public int PERSON_ID { get; set; }
        public string FATHERS_NAME { get; set; }
        public string MOBILE { get; set; }
        public string PHONE { get; set; }
        public string GENDER { get; set; }
        public string MARITAL_STATUS { get; set; }
        public string PERMANENT_ADDRESS { get; set; }
        public string MAILING_ADDRESS { get; set; }
        public string NID { get; set; }
        public string REMARKS { get; set; }
    }
}
