//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_FAMILY
    {
        public int FAMILY_ID { get; set; }
        public Nullable<int> PERSON_ID { get; set; }
        public string MEMBER_NAME { get; set; }
        public string RELATION { get; set; }
        public Nullable<int> AGE { get; set; }
        public string OCCUPATION { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string REMARKS { get; set; }
    
        public virtual PERSON PERSON { get; set; }
    }
}
