//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_DEGREES
    {
        public int PERSON_ID { get; set; }
        public int DEGREE_ID { get; set; }
        public Nullable<int> EDUCATIONAL_DEGREE_ID { get; set; }
        public string INSTITUTE { get; set; }
        public string PASSING_YEAR { get; set; }
        public string SUBJECT { get; set; }
        public string DURATION { get; set; }
        public Nullable<int> GRADE_ID { get; set; }
        public Nullable<decimal> CGPA { get; set; }
        public Nullable<int> DIVISION_ID { get; set; }
        public Nullable<int> MARK { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string REMARKS { get; set; }
    }
}
