//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONS_REFERENCES
    {
        public int PERSON_ID { get; set; }
        public int REFERENCE_ID { get; set; }
        public Nullable<int> REFERENCE_TYPE_ID { get; set; }
        public string REFERENCE_NAME { get; set; }
        public string ORGANAIZATION { get; set; }
        public string DESIGNATION { get; set; }
        public string MOBILE { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string MAILING_ADDRESS { get; set; }
        public string RELATIONSHIP { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string REMARK { get; set; }
    }
}
