//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_JOB_EXPERIENCES
    {
        public int PERSON_ID { get; set; }
        public int EXPERIENCE_ID { get; set; }
        public int EXPERIENCE_TYPE_ID { get; set; }
        public string ORGANIZATION { get; set; }
        public string DESIGNATION { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string DURATION { get; set; }
        public string JOB_DESCRIPTION { get; set; }
        public string ACHIEVEMENT { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string REMARKS { get; set; }
    }
}
