//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_SKU
    {
        public PRODUCT_SKU()
        {
            this.FORM_ROW_ITEM = new HashSet<FORM_ROW_ITEM>();
            this.JCOffers = new HashSet<JCOffer>();
        }
    
        public int ProductSKUId { get; set; }
        public string ProductSKUName { get; set; }
        public int ProductId { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<int> PiecePerCarton { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<FORM_ROW_ITEM> FORM_ROW_ITEM { get; set; }
        public virtual ICollection<JCOffer> JCOffers { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
