//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_TYPE
    {
        public PRODUCT_TYPE()
        {
            this.PRODUCTs = new HashSet<PRODUCT>();
        }
    
        public int ProductTypeId { get; set; }
        public string ProductTypeName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<PRODUCT> PRODUCTs { get; set; }
    }
}
