//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFERENCE_TYPES
    {
        public int REFERENCE_TYPE_ID { get; set; }
        public string REFERENCE_TYPE_NAME { get; set; }
    }
}
