//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET_STATUS
    {
        public TICKET_STATUS()
        {
            this.ComplainTickets = new HashSet<ComplainTicket>();
        }
    
        public int StatusId { get; set; }
        public string StatusName { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<ComplainTicket> ComplainTickets { get; set; }
    }
}
