//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET_REPLIED
    {
        public int RepliedId { get; set; }
        public int TicketId { get; set; }
        public Nullable<int> RepliedBy { get; set; }
        public Nullable<System.DateTime> RepliedTime { get; set; }
        public string ContentText { get; set; }
    
        public virtual ComplainTicket ComplainTicket { get; set; }
    }
}
