//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_TYPES
    {
        public int USER_TYPE_ID { get; set; }
        public string USER_TYPE_NAME { get; set; }
        public string USER_TYPE_FULL_NAME { get; set; }
        public Nullable<int> PROJECT_ID { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<bool> INCLUDE_FOR_ADMIN_CONTENT { get; set; }
    }
}
