//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS_LOGIN_INFO
    {
        public int LOG_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> EMPLOYEE_ID { get; set; }
        public System.DateTime LOGIN_DATE { get; set; }
        public string REMARK { get; set; }
        public string IMAGE_ID { get; set; }
        public Nullable<decimal> LAT { get; set; }
        public Nullable<decimal> LON { get; set; }
    }
}
