//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewDistributionHouseSpecificPosition
    {
        public int PositionId { get; set; }
        public string PositionName { get; set; }
        public Nullable<int> PositionTypeId { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public int EmployeeId { get; set; }
        public int HouseId { get; set; }
    }
}
