//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Supervisors
    {
        public int EMPLOYEE_ID { get; set; }
        public Nullable<int> SUPERVISOR_ID { get; set; }
        public string SupervisorName { get; set; }
        public string SupervisorPhoto { get; set; }
    }
}
