//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_EmployeeListForAssignToParent
    {
        public Nullable<int> DistributionHouseId { get; set; }
        public Nullable<int> PersonCurrentStatusId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int EmployeeId { get; set; }
        public string EmployeeCode { get; set; }
        public string PersonName { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public string NID { get; set; }
        public int DesignationId { get; set; }
        public Nullable<int> EmployeeTypeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> MarritalStatusId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string DistributionHouseName { get; set; }
        public string Photo { get; set; }
        public string EmployeeTypeName { get; set; }
        public Nullable<int> PROJECT_ID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> SupervisorId { get; set; }
        public string SupervisorName { get; set; }
        public string SupervisorPhoto { get; set; }
    }
}
