//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_EMPLOYEES
    {
        public int EMPLOYEE_ID { get; set; }
        public int PERSON_ID { get; set; }
        public string PERSON_NAME { get; set; }
        public Nullable<int> EMPLOYEE_TYPE_ID { get; set; }
        public string EMPLOYEE_TYPE_NAME { get; set; }
        public Nullable<int> DISTRIBUTION_HOUSE_ID { get; set; }
        public string DISTRIBUTION_HOUSE_NAME { get; set; }
        public Nullable<int> LOCATION_ID { get; set; }
        public string LOCATION_NAME { get; set; }
        public string EMPLOYEE_CODE { get; set; }
        public Nullable<int> SUPERVISOR_ID { get; set; }
        public Nullable<int> OFFICE_ID { get; set; }
        public Nullable<int> BRAND_ID { get; set; }
        public string BRAND_NAME { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string MAILING_ADDRESS { get; set; }
        public string HOUSE_PHONE { get; set; }
        public Nullable<bool> SIGNATURE_PRESENT { get; set; }
        public string SIGNATURE_PATH { get; set; }
        public Nullable<bool> PHOTO_PRESENT { get; set; }
        public string PHOTO_PATH { get; set; }
        public string REMARKS { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CRAETED_DATE { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public Nullable<int> DISTRICT_ID { get; set; }
        public Nullable<int> THANA_ID { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<int> KCP_DESIGNATION_ID { get; set; }
        public string KCP_NAME { get; set; }
        public string KCP_MOBILE { get; set; }
        public string KCP_EMAIL { get; set; }
        public string FATHERS_NAME { get; set; }
        public string MOTHERS_NAME { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public Nullable<int> RELIGION_ID { get; set; }
        public string RELIGION_NAME { get; set; }
        public string RELIGION_SPECIFY { get; set; }
        public string NATIONALITY { get; set; }
        public Nullable<int> GENDER_ID { get; set; }
        public string GENDER_NAME { get; set; }
        public Nullable<int> MARITAL_STATUS_ID { get; set; }
        public string MARITAL_STATUS_NAME { get; set; }
        public string PERMANENT_ADDRESS { get; set; }
        public string MOBILE { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string NID { get; set; }
        public Nullable<int> PERSON_CURRENT_STATUS_ID { get; set; }
        public string PERSON_CURRENT_STATUS_NAME { get; set; }
        public Nullable<bool> PERSON_ACTIVE { get; set; }
        public string PERSON_REMARKS { get; set; }
        public Nullable<int> EMPLOYEE_ROLE_STATUS_ID { get; set; }
        public string EMPLOYEE_ROLE_STATUS_NAME { get; set; }
        public int DESIGNATION_ID { get; set; }
        public string DESIGNATION_NAME { get; set; }
        public string DISTRICT_NAME { get; set; }
        public string THANA_NAME { get; set; }
        public string PERSON_IMAGE { get; set; }
        public Nullable<int> BANK_ID { get; set; }
        public string BANK_NAME { get; set; }
        public string BANK_BRANCH { get; set; }
        public string BANK_ACCOUNT_NO { get; set; }
        public Nullable<System.DateTime> JOINING_DATE { get; set; }
        public Nullable<long> MINIMUM_INVESTMENT { get; set; }
        public string OTHER_FINANCIAL { get; set; }
        public string SERVICE_DESCRIPTION { get; set; }
        public string PREVIOUS_PD_DETAIL { get; set; }
        public Nullable<int> FAMILY_MEMBER_NO { get; set; }
        public Nullable<int> MALE_NO { get; set; }
        public Nullable<int> FEMALE_NO { get; set; }
        public string EDUCATIONAL_QUALIFICATION { get; set; }
    }
}
