//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PERSON
    {
        public int PERSON_ID { get; set; }
        public string PERSON_NAME { get; set; }
        public string FATHERS_NAME { get; set; }
        public string MOTHERS_NAME { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public Nullable<int> RELIGION_ID { get; set; }
        public string RELIGION_NAME { get; set; }
        public string RELIGION_SPECIFY { get; set; }
        public string NATIONALITY { get; set; }
        public Nullable<int> GENDER_ID { get; set; }
        public string GENDER_NAME { get; set; }
        public Nullable<int> MARITAL_STATUS_ID { get; set; }
        public string MARITAL_STATUS_NAME { get; set; }
        public string PERMANENT_ADDRESS { get; set; }
        public string MAILING_ADDRESS { get; set; }
        public Nullable<int> DISTRICT_ID { get; set; }
        public string DISTRICT_NAME { get; set; }
        public Nullable<int> THANA_ID { get; set; }
        public string THANA_NAME { get; set; }
        public string MOBILE { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string NID { get; set; }
        public Nullable<int> PERSON_CURRENT_STATUS_ID { get; set; }
        public string PERSON_CURRENT_STATUS_NAME { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<int> DISTRIBUTION_HOUSE_ID { get; set; }
        public string DISTRIBUTION_HOUSE_NAME { get; set; }
        public Nullable<int> ENTERED_BY_ID { get; set; }
        public string ENTERED_BY_NAME { get; set; }
        public Nullable<System.DateTime> ENTERED_DATE { get; set; }
        public Nullable<int> UPDATE_BY_ID { get; set; }
        public string UPDATE_BY_NAME { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string PERSON_IMAGE { get; set; }
    }
}
