//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollidut.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_USERS
    {
        public int USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string LOGIN_NAME { get; set; }
        public string PASSWORD { get; set; }
        public int USER_TYPE_ID { get; set; }
        public string USER_TYPE_NAME { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<int> EMPLOYEE_ID { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public Nullable<int> DISTRIBUTION_HOUSE_ID { get; set; }
        public string DISTRIBUTION_HOUSE_NAME { get; set; }
        public Nullable<int> AREA_ID { get; set; }
        public string AREA_NAME { get; set; }
        public Nullable<int> REGION_ID { get; set; }
        public string REGION_NAME { get; set; }
    }
}
